#  ___        _  ___           __ _
# | _ \___ __| |/ __|_ _ __ _ / _| |_   ___ _ _ __ _
# |   / -_) _` | (__| '_/ _` |  _|  _|_/ _ \ '_/ _` |
# |_|_\___\__,_|\___|_| \__,_|_|  \__(_)___/_| \__, |
#                                              |___/
#
# A BungeeCord plugin to handle chat on Minecraft and Discord

# This is for your Discord bot
discord-enabled: true
discord-token: ''
discord-channel-minecraft: 'minecraft'
discord-activity-enabled: true
discord-activity-type: 'default'
discord-activity-value: 'RedCraft.org'

# This is for the translation service
translation-enabled: true
translation-service: 'deepl'
translation-supported-languages: ['en', 'fr']
translation-discord-category-format: '[%lang%] %topic%'
translation-discord-category-template: 'en'

# These are the settings for Deepl live translation
deepl-token: ''
deepl-endpoint: 'https://api.deepl.com/v2/translate' # If you use a proxy or something
deepl-formality: 'less' # can be "normal", "more" or "less". Default is "less" so messages seem more friendly
deepl-preserve-formatting: false # whether the translation engine should respect the original formatting, even if it would usually correct some aspects

# Shorten URLs
url-shortening-enabled: false
url-shortening-service: 'redcraft_url_shortener'
url-shortening-endpoint: 'https://redcraft.org/api/v1/url'
url-shortening-api-token: ''

# Database related settings
# MySQL example: jdbc:mysql://localhost:3306/redcraft_chat?useSSL=false&autoReconnect=true
database-uri: 'jdbc:sqlite:%plugin_config_path%/database.db'
database-username: 'root'
database-password: 'password'

# Used for caching
redis-enabled: false
redis-uri: 'redis://localhost:6379/0'
redis-key-prefix: 'rcbc'
