name: RedCraftChat
main: org.redcraft.redcraftchat.RedCraftChat
version: 0.1.0-SNAPSHOT
author: RedCraft
authors: [lululombard]
permissions:
   redcraftchat.*:
     description: Gives access to all RedCraftChat permissions
     children:
       redcraftchat.formatting.*: true
   redcraftchat.formatting.*:
     description: Allows all kind of formatting
     children:
       redcraftchat.formatting.colors: true
       redcraftchat.formatting.styling: true
       redcraftchat.formatting.magic: true
   redcraftchat.formatting.colors:
     description: Allows color in chat
   redcraftchat.formatting.styling:
     description: Allows styling in chat
   redcraftchat.formatting.magic:
     description: Allows magic (&k) in chat
